name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write   # for OIDC
  contents: read

jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590807097490:role/pce-dev-ci
          aws-region: eu-north-1

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      # 🔑 Fix: Install and enable pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version

      - run: echo "✅ CI wiring OK – starting synth"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: CDK Synth
        run: pnpm --filter @pce/infra run cdk synth

      - uses: actions/upload-artifact@v4
        with:
          name: cdk-template
          path: cdk.out/PceApp-dev.template.json
