name: ci
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'      # cache removed to avoid lockfile requirement

      - run: pnpm -r install      # or: pnpm -r i
      - run: pnpm -r build || echo "no build yet"

  cdk-synth:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'      # cache removed to avoid lockfile requirement

      - run: pnpm -r install

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590807097490:role/PceCICDDeployRole
          aws-region: af-south-1

      - run: pnpm -w --filter infra cdk synth
