permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590807097490:role/PceAppDev-GitHubOIDC
          aws-region: eu-north-1

      - name: CDK Deploy
        run: pnpm --filter @pce/infra run cdk deploy PceApp-dev --require-approval never
